main: ${groupId}.${pluginPackage}.bukkit.BukkitPlugin
name: ${artifactId}
version: ${project.version}
author: MTC
softdepend: [ProtocolLib,ViaVersion,ProtocolSupport]
commands:
  clientstats:
    description: Access to ClientStats commands
    usage: /clientstats
    aliases: [cstats,cs,sclientstats,scstats,scs]
