messages:
    commands:
        help:
        - "&7Aide: ClientStats"
        - "&b/clientstats joined &7- Nombre de joueurs ayant rejoins"
        - "&b/clientstats version &7- Version des joueurs ayant rejoins"
        - "&b/clientstats online &7- Version des joueurs en ligne"
        - "&b/clientstats player [joueur] &7- Version d'un joueur"
        - "&b/clientstats reload &7- Recharger le plugin"
        player:
            self: "Tu es en version {1}."
            other: "&a{1}&f est en version {2}."
            not-found: "Le joueur &a{1}&f n'a pas été trouvé."
        joined:
            unique: "{1} joueurs différents ont rejoins le serveur."
            total: "Il y a eu {1} connexions au serveur."
        version:
            title: "Version des joueurs ayant rejoins le serveur:"
            list: "&a{1}&f joueurs en version {2}"
            empty: "Aucun joueur n'a rejoins le serveur !"
        online:
            title: "Version des joueurs sur le serveur:"
            list: "&a{1}&f joueurs en version {2}"
            empty: "Aucun joueur n'est sur le serveur !"
        reload: "Le plugin a été rechargé !"
    error:
        permission: "&cTu n'as pas la permission !"
        not-a-player: "Tu n'es pas un joueur !"
        general: "&cUne erreur est survenue.."

versions:
    "0": "Inconnu"
    "47": "1.8 - 1.8.6"
    "46": "1.8 pre3"
    "45": "1.8 pre2"
    "44": "1.8 pre1"
    "43": "14w34d"
    "42": "14w34c"
    "41": "14w34b"
    "40": "14w34a"
    "39": "14w33c"
    "38": "14w33b"
    "37": "14w33a"
    "36": "14w32d"
    "35": "14w32c"
    "34": "14w32b"
    "33": "14w32a"
    "32": "14w31a"
    "31": "14w30c"
    "30": "14w30a"
    "29": "14w29a"
    "28": "14w28b"
    "27": "14w28a"
    "26": "14w27a, 14w27b"
    "25": "14w26c"
    "24": "14w26b"
    "23": "14w26a"
    "22": "14w25b"
    "21": "14w25a"
    "20": "14w21b"
    "19": "14w21a"
    "18": "14w20a"
    "17": "14w19a"
    "16": "14w18b"
    "15": "14w17a"
    "14": "14w11a"
    "12": "14w08a"
    "11": "14w07a"
    "10": "14w06a"
    "9": "14w05a"
    "8": "14w04b"
    "7": "14w04a"
    "6": "14w03a"
    "5": "1.7.6 - 1.7.10"
    "4": "1.7.1 - 1.7.5"
    "78": "1.6.4"
    "74": "1.6.2"
    "73": "1.6.1"
    "72": "13w26a, 1.6-pre"
    "71": "13w25a, 13w25b, 13w25c"
    "70": "13w24b"
    "69": "13w24a"
    "68": "13w23b"
    "67": "13w21a, 13w21b, 13w22a, 13w23a"
    "66": "13w19a"
    "65": "13w18a"
    "64": "13w17a"
    "63": "13w16b"
    "61": "1.5.2"
    "60": "1.5 - 1.5.1"